#!/usr/bin/env python3

import sys

from rqt_gui.main import Main

from turtle_gui.control import Control

plugin = 'turtle_gui.control.Control'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
